### ISSUE TITLE
LGit_GIT_ERROR: error authenticating: no auth sock variable loading a Tonel based baseline dependency in smalltalkCI

### ISSUE THREAD

**Issue by gcotelli** [pharo-vcs/iceberg#643]
smalltalkCI now supports the tonel file format and the iceberg-metacello integration is not disabled anymore.

Loading a project depending in another project both in Tonel format gives this error on Pharo 7:
```Loading baseline of BaselineOfBoardwalk...LGit_GIT_ERROR: error authenticating: no auth sock variable
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
IceGitScpRemote(IceGitRemote)>>cloneIn:subdirectory:
IceRepositoryCreator>>cloneRepository
```

Checkout https://travis-ci.org/ba-st/Boardwalk/jobs/368090233

In Pharo 6.1 is working Ok.

**Comment by estebanlm** [comment]
should be fixed on 0.7.3

**Comment by gcotelli** [comment]
This is supposed to be fixed. But it's still failing with the latest pharo 7 version. Checkout this build from today: https://travis-ci.org/ba-st/Willow/jobs/373448344

**Comment by guillep** [comment]
Ok, I assume the problem is that Iceberg is not catching the "absence of ssh agent" error. I'll try to get a way to reproduce it in a test

**Comment by guillep** [comment]
Ok, it was apparently that. In #752 I've introduced:
 - new metacello integration tests for it that run on the CI
 - some architectural renraku rules to validate that we are correctly handling errors
 - plus a pass on iceberg to check all violated rules

**Comment by gcotelli** [comment]
Thanks Guille, when this is merged in Pharo I can test easily my projects
in smalltalkCI/travis so we can know if it's working.

**Comment by jecisc** [comment]
What is really weird is that it works in Pharo 6.1 but not 7.

I have the same problem with one of my project.

**Comment by guillep** [comment]
@gcotelli I'd like to build a more interesting integration test for it in the CI. Can you tell me if this happens only for tonel projects or also for filetree? I'd say it should happen for both...

@jecisc Iceberg - metacello integration in pharo 6 is disabled by default :)

**Comment by jecisc** [comment]
It know works:

https://travis-ci.org/TelescopeSt/Telescope/jobs/373994423

**Comment by guillep** [comment]
@gcotelli can you confirm if this works on your side too? If so, I'll close this issue :)

**Comment by gcotelli** [comment]
It works now. Thanks.

**Comment by guillep** [comment]
Nice! Thanks
